### ISSUE TITLE
Allow clients to specify transformations to incoming images

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#246]
Currently the only way to change incoming images in Imbo is to add event listeners to the server configuration. It would be a nice addition if clients could specify transformations to be applied to new images before Imbo stores them.

This could be accomplished by allowing clients to send content types of `multipart/form-data`, where they include the file to be added along with transformation parameters as a `$_POST['t']` array (for instance).

**Comment by christeredvartsen** [comment]
If we are to implement this I think the server should decide whether or not to allow it. Thoughts @matslindh?

**Comment by matslindh** [comment]
I can see the use for inbound transformations - my suggestion would be to allow the server to configure a transformation sequence that can be applied on input (if the client requests it). That way we can limit it to the the transformations we want to expose (and the server has to be explicitly configured for it), while supporting transformation sequences as we do on output as well.
