### ISSUE TITLE
Global image search

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#259]
Imbo needs a global image search that should be able to list images across all public keys.

For this Imbo needs a master key of sorts that is used to sign the requests. The response payload should match the one from the existing `/users/<user>/images` resource and should support all the same query params.

**Comment by kbrabrand** [comment]
As a consequence of missing support for the `SEARCH` verb in the built-in server shipped with PHP, we're not able to test `SEARCH` operations in Imbo with the current behat setup.

What do you think – should we wait for PHP to implement support or should we use some other keyword/endpoint? The guzzle client is missing support for `GET` with request body (in the RequestFactory at least), so I don't think that's a good alternative either.

Input please.

**Comment by rexxars** [comment]
Since this is missing the latest status, let me update with the latest: A workaround in now in place - specifying `X-HTTP-Method-Override` will override the original HTTP method.

**Comment by rexxars** [comment]
This task is now solved when #330 lands, and is paired with [https://github.com/imbo/imbo-metadata-search](imbo-metadata-search).

**Comment by kbrabrand** [comment]
Closed with #348

**Comment by rexxars** [comment]
Closing this, as the functionality is available with the global images endpoint paired with https://github.com/imbo/imbo-metadata-search.
