### ISSUE TITLE
Global image endpoint

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#261]
Imbo should have a global image endpoint that can be used together with the global images endpoint. In theory two images can have the same MD5 sum, but the global image endpoint should just do a `limit 1` of sorts when querying the backend, and simply fetch the first image with the given image identifier.

**Comment by rexxars** [comment]
See #330.

**Comment by rexxars** [comment]
Do we still think this is a good idea? I don't really see the need for this now that we have public keys that can access multiple users.

**Comment by kbrabrand** [comment]
No. I don't see the big point of having this double up; here and on the images resource with a public key that has access to some random user.

**Comment by rexxars** [comment]
Closing this - if people still see some need for this, it should be trivial to implement as a custom resource.
