### ISSUE TITLE
Use UUIDs instead of MD5 for image identifiers

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#263]
When `1.0.0` was released the clients no longer needs to generate image IDs so that Imbo now uses MD5 is an implementation detail.

Should Imbo use UUIDs instead? If so I want to use native PHP to generate the IDs, and not rely on a custom extension.

One solution is to use [Rhumsaa\Uuid](https://github.com/ramsey/uuid).

**Comment by rexxars** [comment]
Implemented and merged UUIDs in #347. Will consider doing the modifications necessary to support the full base64 range of characters, which would allow us to switch the UUIDs to "basically anything".
