### ISSUE TITLE
incorrect content-type header - corrupted images

### ISSUE THREAD

**Issue by bazo** [imbo/imbo#299]
Hi, it's me again with the corrupted images :) i would like to continue on this issue https://github.com/imbo/imbo/issues/245

Yesterday i dug deeper to find the cause and came up with these findings:
i used a jpeg image. 

on firefox and ie, when i put the image url into an <img> tag, the image is being served as image/png, because the browser sends accept: image/png. it seems to affect only images larger than ~200x200px whether original or resized via imbo. 

also this message appears in nginx error log [crit] 11707#0: *2194 open() "/var/lib/nginx/fastcgi/3/14/0000000143" failed (13: Permission denied) while reading upstream. upstream: "fastcgi://unix:/var/run/php5-fpm.sock:" this error shows up only when the image displays as corrupted, so something in imbo is messing it up

if i view the image directly from the url, content type is correct.

on chrome and opera the content type is correct image/jpeg for img tag and also direct.

here are all the headers http://grabberapp.com/qlqj6x

**Comment by rexxars** [comment]
After only 1.5 years I finally had a look at this, but I'm unable to reproduce. Couldn't get hold of the mentioned version of ImageMagick, but the old releases has so many issues that I'm going to go ahead and say the problem will most likely go away with a more recent imagick release.
