### ISSUE TITLE
Make error verbosity configurable

### ISSUE THREAD

**Issue by androa** [imbo/imbo#323]
As raised in https://github.com/imbo/imbo/issues/322#issuecomment-74027527 the verbosity of errors should be configurable.

**Comment by androa** [comment]
Should it also be configurable if the information should be put into logs instead? Or even per public key?

**Comment by christeredvartsen** [comment]
I'm thinking that the error page(s) should show info, or not. I don't feel it's necessary to configure how much to show, but that's just my point of view.

Might be a nice addition to be able to do this by public key as well as you mention.

I feel that logging is a separate topic (add info to #318).

**Comment by christeredvartsen** [comment]
What do people think is the way to solve this? Having some configuration flag for `showInfoOnErrors` or something similar? Configurable pr user and/or public key as well?
