### ISSUE TITLE
Modularizing/pluginification of Imbo

### ISSUE THREAD

**Issue by androa** [imbo/imbo#324]
The architecture of Imbo is already inherently very plugin-oriented. With the massive raise of Composer for dependency management, and the focus on building smaller services and modules I want to propose splitting Imbo up in smaller and more logical areas of concerns.

Imbos event-oriented flow allows features to be written as loosely coupled plugins that could also be installed with Composer.

My proposal for dividing the concerns:
 - Core (config, event-manager, etc) + pure image upload and transformations.
  - Hereunder the existing DB/Storage adapters could also be extracted if it seems logical.
 - Metadata - Todays metadata feature could be extracted directly.
 - Search
 - Master archive - a less performant, but cheaper, write-only long-term storage.
 - Usage statistics - view count, unique transformations, etc.

Negative aspects by doing this is that it requires a bit more work setting up Imbo the first time, and will increase the need for installing with Composer (git clone would still work, but even more work).

**Comment by christeredvartsen** [comment]
We have started creating plugins as separate packages, and have another issue that proposes moving some parts out of Imbo (#408). Since this seems to be the direction we are going I'm closing this issue for now.
