### ISSUE TITLE
Fatal error when using guzzle v3.7.4

### ISSUE THREAD

**Issue by sgulseth** [imbo/imbo#335]
When using guzzle v3.7.4 getImageUrl throws a fatal error
`Fatal error: Call to undefined method Guzzle\Http\Url::setPrivateKey() in /home/henkjers/webdev/e24/vendor/imbo/imboclient/src/ImboClient/Http/Url.php on line 40`

Upgrading to guzzle v3.9.2 fixed the issue

**Comment by rexxars** [comment]
This is an error with the *client*, right? Wrong repo in that case. What's even weirder is that the composer  file says we require guzzle 3.8, so I'm not really sure why it would be using 3.7?

**Comment by sgulseth** [comment]
Yes, this should be in the imbo-client, my bad! 

Another package we are using required guzzle 3.7 and composer didn't complain when installing imboclient 1.2

**Comment by rexxars** [comment]
I still don't understand how this can fail. Given the following `package.json`:
```json
{
    "require": {
        "guzzle/guzzle": "~3.7.4",
        "imbo/imboclient": "1.2.0"
    }
}
```

When running `composer install`, I get the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for imbo/imboclient 1.2.0 -> satisfiable by imbo/imboclient[1.2.0].
    - imbo/imboclient 1.2.0 requires guzzle/guzzle ~3.8 -> no matching package found.
```

While that error could certainly be a little clearer, it seems to be doing what it's supposed to here. Closing this, and if someone runs into this again, we can continue to discuss it in the [imboclient-php](https://github.com/imbo/imboclient-php) issues.
