### ISSUE TITLE
Imbo support https?

### ISSUE THREAD

**Issue by haibt** [imbo/imbo#337]
I have installed Imbo, with nginx server, it runs well with http protocol.
When I change to use SSL cert installed on nginx, imbo could not process. Should I change anything in configuration of Imbo?

**Comment by rexxars** [comment]
Yes, Imbo supports HTTPS. There's a couple things to consider, however:

* URLs generated from a client must be created with the correct protocol (you cannot simply replace http with https in an image URL containing an accesstoken). For instance, if you're using the PHP client, you need to pass HTTPS host URLs to the client when creating it:
```php
$client = ImboClient\ImboClient::factory(array(
    'serverUrls' => array('https://imbo.example.com'),
    'publicKey' => 'user',
    'privateKey' => 'private key',
));
```
* If you have a reverse proxy or some other software terminating your HTTPS before passing it on to nginx, you might have to configure the `trustedProxies` setting. For instance, `'trustedProxies' => ['192.0.0.1', '10.0.0.0/8']`. From what you're writing it sounds like you are using HTTPS directly through nginx though, so this shouldn't be required.

What is actually failing for you? Are images failing to be added? Are images failing to be displayed? Take a look at the responses from Imbo - they should hopefully be descriptive enough to let us help you further.

**Comment by rexxars** [comment]
Closing this since no more information was provided.
