### ISSUE TITLE
OPTIONS-requests for CORS not Vary'ing on Origin

### ISSUE THREAD

**Issue by fangel** [imbo/imbo#338]
Hi,

We ran in to a problem where the CORS headers would return a different allowed origins than the (whitelisted) origin that was sent with the request.
I think this might be because the `Vary`-header isn't updated to include `Origin` on the `OPTIONS`-request, like it is for the `GET` requests.. So if the `OPTIONS`-request is cached by Varnish, it is the same cache for all origins, and thus only the first allowed origin is stored in the cache...

In `Imbo\EventListener\Cors`, the method `options` doesn't update the `Vary`-header, but the `invoke`-method does, with the code

````php
// Vary on Origin to prevent caching allowed/disallowed requests
$event->getResponse()->setVary('Origin', false);
````

Is there a good reason why this is the case, or is it just because it's been forgotten to add it in the `options`-method?

Kind regards
Morten

**Comment by rexxars** [comment]
This seems like an oversight. If you are send a pull request that includes a test, I'll happily merge it. Otherwise I'll see if I can find the time to do it tomorrow.

**Comment by fangel** [comment]
I can update the test-cases and code - it might be tomorrow before I have time, but I will get around to it at some point :).

There are actually already a test for the non-`OPTIONS`-requests to include `Origin` in the `Vary`-header, so it shouldn't even require any new test-step-definitions (is that the right Behat word?) to add the same check to the `OPTIONS`-requests
