### ISSUE TITLE
Empty response from users access point

### ISSUE THREAD

**Issue by mmontone** [imbo/imbo#346]
Hello.
I have a problem with imbo
when trying to get info from a user, I get nothing, an empty response
```
curl http://imbo/users/<user>.json?accessToken=<token>
```
same with ``` -H 'accept: application/json' ```
what could be the problem?
the access token seems to be correct, as I'm not getting an "invalid token" error

**Comment by mmontone** [comment]
Oh. Now I see it is an Internal Server Error

But I'm clueless about what could be wrong.

How can I debug this?

http://imbo responds ok.

**Comment by mmontone** [comment]
http://imbo/status also returns 500 error

I think this could be a database connection error, but I can't see the error, and mongodb is up and running on default port.

**Comment by kbrabrand** [comment]
The PHP error log probably contains clues on what's wrong. Also the [Imbo docs](http://imbo.readthedocs.org/en/latest/) contains useful information on how to interact with the server. 

If you're unable to figure it out please post your config file and whatever error message you're getting in the error log.

**Comment by mmontone** [comment]
Inspected the apache logs. 

I found this: 

```
PHP Fatal error:  Class 'MongoClient' not found in /home/marian/src/imbo/vendor/imbo/imbo/library/Imbo/Database/MongoDB.php on line 623
```

I installed Imbo with Composer

**Comment by rexxars** [comment]
You are missing the Mongo extension  for php. 

How you install it depends on your operating system / setup. If you are running a Debian based distribution, you can do: `sudo apt-get install php5-mongo`

**Comment by mmontone** [comment]
Yes. I see. Sorry. I was not aware that MongoDB came as an PHP extension. Thanks for your help!
