### ISSUE TITLE
Access control: Create a "SimpleArrayAdapter"?

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#354]
Currently we have some logic that translates the old `auth` public/private key configuration into the more complicated but flexible access control setup. While this is transparent for most users in terms of backwards compatibility, I think it would be nice if we moved all this logic to a separate adapter that could be used as an alternative, should you not require all the flexibility the new setup gives you.

In other words, instead of doing:
```php
<?php
return [
    'accessControl' => function() {
        return new ArrayAdapter([
            [
                'publicKey' => 'espenh',
                'privateKey' => 'myprivatekey',
                'acl' => [[
                    'users' => ['espenh'],
                    'resources' => ArrayAdapter::getReadWriteResources()
                ]]
            ]
        ])
    }
];
```

One could simply do:
```php
<?php
return [
    'accessControl' => function() {
        return new SimpleArrayAdapter([
            'espenh' => 'myprivatekey'
        ])
    }
];
```

Basically the exact same configuration format passed as the `auth` key in the configuration today.

The simple adapter could simply map this to the array structure expected by `ArrayAdapter` and pass it on to that, basically reusing all the logic.

**Comment by kbrabrand** [comment]
Closed with #355
