### ISSUE TITLE
Change contrastImage to use sigmoidalContrastImage?

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#384]
Currently, we're doing some pretty nasty for-loops in the contrast transformation to sharpen the image "more than once". Instead, we should probably look at `sigmoidalContrastImage()` in imagick which would probably be more performant (and certainly a lot cleaner).

**Comment by rexxars** [comment]
I've done a bit of testing on this. While you don't necessarily save much performance by using `sigmoidalContrastImage`, you can get (in my opinion) significantly better results. I'm not a photo-wiz, but what I expect when using a contrast transformation is somewhat the same thing that would happen if I adjusted the "contrast"-slider in for instance Gimp. I've made an alternative implementation, and want your feedback. Obviously, anyone using the contrast transformation might be in for a surprise when they upgrade, but if we merge this into 2.0 I think that's fine.

Here's a comparison of the old (left) and the new (right), with different "sharpen" levels:

![imbo-contrast_mini 1](https://cloud.githubusercontent.com/assets/48200/11102619/e345cba6-88bd-11e5-86cf-d634ce359b11.jpg)

Thoughts?
/cc @kbrabrand @christeredvartsen @matslindh @androa

**Comment by kbrabrand** [comment]
Based on the example images provided I'd say this is a no-brainer. :+1:

**Comment by kbrabrand** [comment]
One question though: the -0.25 example of the new one seem to have higher contrast than the original. Is that right?

**Comment by matslindh** [comment]
All for this change as well. +1

But yes, the examples seem weird around 0 > x > -4.5.

The old and new values might not be comparable directly.

**Comment by rexxars** [comment]
Yeah, I'm having a bit of difficulty getting a gliding transition when going below 0. I'll look into it some more.

**Comment by matslindh** [comment]
After reading into the sigmoidal algorithm a bit, being able to change the
midpoint as well could be useful.

Are you giving the first parameter as x < 0 and then abs(x) as the actual
contrast value?

**Comment by rexxars** [comment]
I've made `alpha` and `beta` configurable. A sane default for `beta` seems to be 0.5, but I'm still struggling to figure out whats going on once you pass into the negative alphas.

Right now it's `$imagick->sigmoidalContrastImage($alpha > 0, $alpha, $beta * $quantumRange)`
Doesn't seem to be any difference between using absolute values for alpha, for some reason. -5 is treated the same as 5.

**Comment by rexxars** [comment]
If I set `$beta = $quantumRange`, giving an `alpha` of `0.25` looks about the same as the unmodified image, but once the alpha increases the image just gets whiter instead of decreasing the contrast.

**Comment by rexxars** [comment]
Turns out I was using an ancient version of ImageMagick (thanks, Ubuntu). Upgraded to the latest version and things worked as expected. Results below, with `beta` set to `0.5`. Configurable.

![imbo-contrast_mini](https://cloud.githubusercontent.com/assets/48200/11105938/8e37ec88-88d2-11e5-91ed-5452f3beb0a8.jpg)

**Comment by matslindh** [comment]
That seems correct, and a great improvement in quality. +1

**Comment by kbrabrand** [comment]
Awesome :clap:

**Comment by rexxars** [comment]
Implemented in #402.
