### ISSUE TITLE
Allow retrieval of rules for current public key?

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#387]
I've been thinking a lot lately about tooling for Imbo. One of the things that I've been wanting to create is a graphical administration tool. With Imbo 2.0, things are a little more complicated than it once was. For instance, if you enter credentials for a public key that only has access to a few resources, you will get a lot of "access denied"-messages.

I see two possible options:
1. Document and require a given set of resources for the public key (or just accept lots of "access denied"-messages)
2. Let the public key see which resources and users it has access to, without granting access to all public keys

I'm leaning towards the second solution. With this approach, we could hide or disable features that the public key does not have access to. In practice, this would mean modifying the access control implementation to allow a public key access to `/keys/<own-public-key>/access`, without explicitly having defined this in the access control configuration.

To be honest, I don't see any big problems with this. If you're implementing security by not showing what a public key can do, I think you're doing something wrong. In other words: If a person has access to both the public and private key pair, let them also see what they can do with it.

Thoughts?

**Comment by kbrabrand** [comment]
:+1: for alternative number two. Can't see any problems with it. Quite the opposite actually – as a client using this but not having access to the database, it's pretty unintuitive not having a way to check what I can do with the keys.

If I have keys I shouldn't have, nothing can stop me from simply testing all the endpoints anyway, so there's no real security concerns as far as I see it.

**Comment by rexxars** [comment]
Solved in #399.
