### ISSUE TITLE
Feature-request: Blur as transformation

### ISSUE THREAD

**Issue by sgasser** [imbo/imbo#389]
What do you think if we add blur as new transormation?(http://php.net/manual/de/imagick.blurimage.php)

**Comment by rexxars** [comment]
Sounds like a good idea. We'll have to think a little about what we want to support - given Imagick supports:

```
Imagick::adaptiveBlurImage()
Imagick::motionBlurImage()
Imagick::radialBlurImage()
```

**Comment by kbrabrand** [comment]
I think we should support both regular blur, adaptive blur, motion blur and radial blur. I think it makes sense exposing all the parameters for the blur operations but the channel option.

**Comment by rexxars** [comment]
Solved in #400. Note that it's currently only merged into the beta2.0 branch, which will hopefully make it's way to release soon.

**Comment by sgasser** [comment]
Hi @rexxars, @kbrabrand.

Is there any release day or roadmap for 2.0?

Thx,
Stefan

**Comment by rexxars** [comment]
There are two or three trivial PRs I want to get merged, and one that needs a little more research, but shouldn't be too hard. If all goes well 2.0 should be out within a week or two.

**Comment by sgasser** [comment]
:thumbsup:

**Comment by sgasser** [comment]
Hi @rexxars,

any news?

**Comment by rexxars** [comment]
Sorry, started a new job in January, things are a bit hectic. Can't promise anything, but hoping to have some time for this next weekend.

**Comment by rexxars** [comment]
@sgasser I just pushed 2.0.0 out the door. Big changes from 1.2.5, as you might have seen if you have been following the work that's been going on for the past 6 months. Upgrade details: http://docs.imbo.io/en/2.0.0/installation/upgrading.html#imbo-2-0-0
