### ISSUE TITLE
`drawPois` does not draw correctly after crop/resize

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#393]
See #392. Because of coordinates not being correct after cropping/resizing, we're not able to draw the POIs on the correct portion of the image, unless we do it as the first step (eg: before cropping/resizing).

**Comment by rexxars** [comment]
This will be harder then I originally envisioned. For instance, imagine cropping, resizing, rotate 19.7339 degrees and cropping again, then try to draw at the correct coordinates. I'm not sure this is easily fixable. For now, I think perhaps documenting this shortcoming in the docs might be a good first step.

**Comment by rexxars** [comment]
Note added in 2aaa3fcf452f79b6c1a9c97f32fd95b964a7749f. Leaving this open for a while to see if we can come up with some solution for this.

**Comment by matslindh** [comment]
Solving an issue like this would probably require us to keep a
transformation/rescale matrices available that modules could use to
calculate their raster position before doing anything to the image. This
would mean that Imbo would support a set of operations and that the
different plugins would change these values (crop would change the world
display window, rotation would change the rotation matrix, etc.), and these
would then be applied in sequence after each plugin had registered their
transformation.

This would match how OpenGL or D3D handles part of their graphics API
today, but would require a change deep into the core of Imbo. I think it'd
be better to just document that the poi feature should be as early as
possible in the set of transformations, and possibly error out if it's
applied after crop/rotate/etc.

**Comment by kbrabrand** [comment]
Gist showing size of bounding box for rotated rectangle: https://gist.github.com/kbrabrand/7d1e81b29243fc899ca3. Might come in handy when drawing POIs on images that has been rotated.
