### ISSUE TITLE
Investigate access token signing with multibyte characters

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#396]
There seems to be a mismatch with URLs containing special characters (`å` in this case), and the access token generated by imboclient-js and Imbo.

For instance:
`https://imbo.host.com/users/user/images/bTA2oSqxVxhp.jpg?name=b%C3%A5t.jpg&mimetype=image/jpeg&t%5B%5D=maxSize%3Awidth%3D158%2Cheight%3D158&publicKey=foo&accessToken=moo`

The character isn't part of the regular image URLs generated, obviously, but it should still be able to generate the same access token.

Also investigate if this is a problem with request signatures.

**Comment by matslindh** [comment]
Could this be caused by utf-8 vs utf-16?

**Comment by rexxars** [comment]
Guessing it's some multibyte kind of thing. We'll see 👍

**Comment by rexxars** [comment]
The problem was caused by the SHA256 library used in `imboclient-js` not generating correct hashes when the data contained characters outside the ASCII range.

https://github.com/imbo/imboclient-js/pull/24 addresses this issue.
