### ISSUE TITLE
Refactor metadata cache?

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#408]
Currently, the metadata cache listener works only for the metadata resource. We're starting to get some transformations (like `smartSize`) that utilize metadata, and as of now there is no clean way for them to use the cache listener.

I don't have a clear picture of how this should be refactored, but I do think we should try to find a way.

**Comment by rexxars** [comment]
After giving this some more thought, I'd not only like to refactor how this is implemented, but ideally I think we should move this to a separate package. Right now, the metadata cache is the only thing using the caching adapters, so if we move the metadata cache we to a separate package, we could also move the cache adapters.

This would allow us to run the main Imbo tests without memcached and apc(u), which would be nice.

**Comment by christeredvartsen** [comment]
Sounds like a good idea.

**Comment by christeredvartsen** [comment]
The `MetadataCache` event listener has now been moved to https://github.com/imbo/imbo-metadata-cache. The listener along with the two cache adapters have been moved (ed8db7380d15fa99adca151ad07b2c3f02041a52 and bceeba60618c64aa24b551986a0a6dc8ff8e0304).
