### ISSUE TITLE
Disallow `.` in group names

### ISSUE THREAD

**Issue by rexxars** [imbo/imbo#409]
The `.`-character creates a bit of confusion both in MongoDB and in terms of URIs (`/groups/group.name.json` etc)

**Comment by rexxars** [comment]
We should probably apply a very specific regex to group names, so we can validate them on the server as well. Maybe use the same regex as for users?

`[a-z0-9_-]{1,}`

**Comment by kbrabrand** [comment]
Yes. That's what I'm thinking. :+1:

**Comment by kbrabrand** [comment]
The group name is already validated in the router, so this is not an issue..
