### ISSUE TITLE
Handle deterministic image identifier generators

### ISSUE THREAD

**Issue by kbrabrand** [imbo/imbo#412]
When using the Md5 image identifier generator the same image will always generate the same identifier. As a consequence of this, Imbo will retry the generator until the max number of retries (currently 100 by default) and effectively md5 the image blob 100 times before giving up with an error.

Since deterministic image identifier generator is something we might want for other generators as well we should add a method to the generator interface `isDeterministic` that indicates whether or not the image identifier generator will return the same identifier for the same image.

If the image identifier generator is deterministic and the generated identifier exists already the response should indicate that in the request response, in the same fashion as in 1.x.

**Comment by rexxars** [comment]
Solved in #413
