### ISSUE TITLE
Failure to write a file isn't propagated through to the client

### ISSUE THREAD

**Issue by matslindh** [imbo/imbo#421]
If the FileSystem adapter (or the GridFS adapter) fails to actually write the file - for example with a full disk - the store() method returns false. But the code handling the write in StorageOperations does not check the return value, and expects an exception to be thrown if the storage operation fails.

There are two ways around this, either we make the storage adapters throw an exception if the write fails, or we check the return value from store(). The first would require changing most of the storage adapters, while the latter would change the logic in StorageOperations.

I'm in favor of changing the adapters, so we can propagate an exception message up the tree as well (the S3 adapter does this).

**Comment by rexxars** [comment]
I agree with you on this. Would you be able to provide a pull request with tests?

**Comment by rexxars** [comment]
Fixed in #423
