### ISSUE TITLE
Cache entries are overwritten on every request

### ISSUE THREAD

**Issue by i1t2b3** [imbo/imbo#426]
The problem is that cache entries are overwritten on every image request

I can see that the ImageTransformationCache  class has a few callbacks in getSubscribedEvents() method
one of them is
    'response.send' => ['storeInCache' => 10],
and the  Application::run triggers that on every call no matter what
so the image is got from cache and then saved back to cache (written to disk) no matter if it was changed or not

So the real problem for us is probably the race conditions and PHP warnings on this line:
    rename($path. '.tmp', $path);
(.tmp file does not exist by the time this line is called)

How can we have the cache entries remain untouched?

**Comment by rexxars** [comment]
Fixed in #430.
