### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#439]
The docs needs some love. As the feature set in Imbo has grown I feel the docs is somewhat disorganized and outdated. Please use this issue to discuss how we can make the docs better.

I'm pinning this to the `2.2` milestone as I'd like the docs to be fully updated before the next minor release.

**Comment by christeredvartsen** [comment]
We also have a bunch of other tools related to Imbo (clients (PHP, JS +++ ), metadata search, cli tool and so on).

Should we create a separate repository for docs and simply move all docs there or will that be hard to maintain?

**Comment by rexxars** [comment]
Unsure about the "monorepo". I'm a big fan of Gitbook, and think it might be a good idea to structure our docs in a way that makes sense in a "book format". It provides a good way for new users to get an introduction to what Imbo actually is, how it works and then have more fine-grained and detailed documentation near the end. See the [redux docs](http://redux.js.org/docs/basics/DataFlow.html) for an example.

**Comment by christeredvartsen** [comment]
Gitbook looks like a good choice. I'd also like users to see the plethora of clients / tools / plugins and whatnot that is available, but that might be the job or a web site instead perhaps.

**Comment by rexxars** [comment]
We could definitely showcase/mention a lot of them in the "book", but I think perhaps the actual client documentation should be left in separate repos, still. Open to discussing it.
