### ISSUE TITLE
Support PHP-7

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#448]
Today Imbo does not run on PHP-7. This should be a requirement for Imbo-3.0.

**Comment by serieznyi** [comment]
@christeredvartsen 
What does this mean?
Now I test Imbo in docker container with php7 and it works. 
But I can`t use mongodb database what is bad.

**Comment by christeredvartsen** [comment]
@serieznyi You pretty much answered that question yourself. Since most users of Imbo use the MongoDB stuff, and that part does not work on php7 yet, I think this means that "Imbo does not run on php7".

When all adapters are working we can agree that Imbo works on php7.

**Comment by christeredvartsen** [comment]
Resolved in #545
