### ISSUE TITLE
Support other sources for configuration

### ISSUE THREAD

**Issue by androa** [imbo/imbo#454]
The configuration file is currently making it quite cumbersome to run Imbo in containers and quickly spin up new instances. Having the possibility to provide configuration through other sources like MongoDB, Redis, Consul, etc. would make it a lot easier to maintain a large cluster of Imbo hosts.

I propose replacing the config array with a config Interface with getters for the separate parts (eg. getDatabase(), getTransformations(), etc) so it can be different implementations.

Any thoughts?

**Comment by androa** [comment]
This also touches upon #16. Having the configuration in a (centralized) database would also open up possiblities for creating more UIs for adding users, transformations, etc.

**Comment by matslindh** [comment]
I'm in favor of something like this, but I'm skeptical about heving very
specific methods for the different configuration options. That will make it
hard to re-use for external plugins or move functionality out of or into
the core.

Could we use something like get(NS, setting) instead, so we'd have
get('user', 'manager') / get('storage', 'manager'). I'm not sure we need
the NS, but it would make it easier to avoid conflicts with external
plugins.

**Comment by androa** [comment]
With methods for each "setting", the interface will look like this: https://github.com/androa/imbo/blob/b941dbb812d438e021124d311378e6cd7188e7f4/src/Imbo/Config/ConfigInterface.php

We can then also move "complexities" like [supporting callables](https://github.com/imbo/imbo/blob/imbo-3.0/src/Imbo/Application.php#L62-L64) into the specific getter in the implementation.

I'm slightly in favor of having a proper interface, defining the implementation, rather than having one magic "get it all, based on string"-method. It makes it easier to ensure that all implementations supports all the necessary configuration settings.

We could also provide an abstract, implementing the most sane defaults.
