### ISSUE TITLE
Support several buckets for the S3 storage adapter

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#461]
Today the S3 storage adapter is configured to use only one bucket. It should support usage of a single bucket, one bucket pr user, or a combination.

**Comment by matslindh** [comment]
Should we be able to track some metadata for each Image about which bucket
it lives in? That would allow us to extend the Storage Drivers with
multiple locations (i.e. multiple paths or mounts for the Filesystem driver
and multiple buckets for the S3 etc. drivers).

**Comment by matslindh** [comment]
I think this could be implemented as part of #487 - by having a flexible configuration for how the federating adapter should work, we should be able to use a storage adapter per user, a list of adapters per user or a combination of adapters.
