### ISSUE TITLE
Throw exception if required configuration options are missing in S3/B2 adapters

### ISSUE THREAD

**Issue by matslindh** [imbo/imbo#499]
The S3/B2 storage adapters should throw an exception if the required configuration settings are missing. They currently assume that the configuration is present, which can lead to weird issues (such as after an upgrade when the region setting might be missing for the S3 adapter).

**Comment by christeredvartsen** [comment]
Perhaps add a `validateConfiguration` method to the storage / database interfaces and have all implementations implement their own and throw an exception if something is missing?

**Comment by matslindh** [comment]
Changing the interface would break any existing custom adapters, but that might not be an actual issue - I guess the number of custom storage adapters written for Imbo is rather low. We don't have any abstract class to add a default implementation to either, so in general, I think we have two options after introducing a `StorageConfigurationException`:

1. Throw it in the constructor of the storage module, if it needs to validate its configuration 
2. Introduce a `validateConfiguration` method.

The latter will make our interface even broader, for something that _can_, within reason, be ignored by an implementation. I'm not sure if it makes sense to **require** a module to implement a method to check for a valid configuration. 

That being said, I'm not particularly opposed to introducing the method, so either option would work for me.

**Comment by christeredvartsen** [comment]
Putting it in `__construct` makes sense.

**Comment by christeredvartsen** [comment]
Shall we add a `ConfigurationException` or separate `StorageConfigurationException` and `DatabaseConfigurationException`, that both extends `ConfigurationException`?

**Comment by matslindh** [comment]
`ConfigurationException` should be enough. You'd know what kind of module you're creating, and the exception would have the same semantic meaning regardless of the type of module used.

**Comment by matslindh** [comment]
Implemented in #511 for the Storage drivers, not sure if we need it in the DB drivers as they might have default values provided by the library or OS?

**Comment by christeredvartsen** [comment]
If any of the drivers in Imbo do anything specific for any configuration key, they should be validated. If the parameters are simply passed on to other libs I'm not really sure what we should do.

It's worth checking out what type of error handling those libs are doing though, so we could for instance wrap them in a try / catch and throw the `ConfigurationException` exception?

**Comment by matslindh** [comment]
If we find cases where they could throw exceptions themselves in their setup phase, we'll wrap them. But I won't spend the time going through each library's setup to find potential exceptions, so I suggest we handle them if they become visible. I guess most libraries won't thrown further exceptions before an actual connection to a server is made anyway, and we can probably live with that being a library specific exception for now (instead of having to wrap most calls to underlying libraries).

**Comment by christeredvartsen** [comment]
Sounds reasonable.

**Comment by matslindh** [comment]
#511 has been merged so I'm guessing we can close this issue now?

**Comment by christeredvartsen** [comment]
Closing it.
