### ISSUE TITLE
Move all tests to "default" locations

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#507]
Today the Behat and PHPUnit tests are not in default locations, which is not really a big issue, but simply running `./vendor/bin/phpunit` and `./vendor/bin/behat` does not work because of this.

Should we consider moving tests to their default locations? In short this would mean to move the `tests/behat/features` directory and the `behat.yml` configuration file to the project root, and the contents of `tests/phpunit` should be moved to `tests`.

All in all it won't add too much stuff to the root directory, which probably is the main argument **against** doing this.

What do you think? This can be done while fixing #404 and #447.

**Comment by matslindh** [comment]
Do we actually need to move more than the configuration files, though? The config files (behat.yml, phpunit.xml) should both be able to say that tests/behat and tests/phpunit are their default root directories?

I'm running `../../vendor/...` today without any major issues, but anything to make it easier to get started (that includes building the documentation as well straight from the project root) is 👍

**Comment by christeredvartsen** [comment]
Only moving the configuration files should work, yes.

**Comment by matslindh** [comment]
Then that's sounds like a good solution to me - it'll allow us to keep anything related to the tests in its own place, and future test frameworks can live inside `tests/` as well.
