### ISSUE TITLE
Normalize the way of handling the configuration

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#508]
Now that we are going to start to add more features to the CLI application, both the web app and the CLi app should share the way the configuration is handled. Today all this happens in the way-too-magic `Imbo\Application::run` method.

Any thoughts regarding this? I would rather not have to do all the configuration parsing in the CLI application as well (as in resolve callbacks to get the database adapter and so forth...)

**Comment by matslindh** [comment]
Is there any reason why we can't expose API methods that the CLI tool uses to get its tasks done? That way it'll be far easier to reuse the same functionality if someone wants to create alternative frontends to Imbo as well.

This is similar to how it's implemented for (most?) other services.

The exception would be functionality that's written for specific backends, such as any Doctrine or mongodb usability fixes (add-index/etc.) where direct access to the underlying resource makes sense.

**Comment by christeredvartsen** [comment]
As in the CLI application using the resource classes and all? There is a bunch of HTTP-related stuff going on around the app though, but this can of course be silenced in the CLI application for instance.

Or are we thinking about two different things here?

**Comment by matslindh** [comment]
My thought was more in line with letting the CLI application issue commands through the HTTP API interface, instead of using the backend directly. The only exception would be problems that makes Imbo not start at all, but I'm not sure if any such issue could be present.

**Comment by christeredvartsen** [comment]
There are some potential commands that we don't really want to expose through the HTTP API though, like for instance (re)generating image variations (#470) and for instance moving images from one user to another. These are more maintenance-like commands...

**Comment by matslindh** [comment]
Or we could expose a `/admin` endpoint with these commands (with separate authentication), but I see the point of keeping possibly long-running processes outside of an httpd (such as regenerating variations). 

Moving images from one user to another seems well-suited for an admin endpoint.
