### ISSUE TITLE
Local config file variables leak into the main config

### ISSUE THREAD

**Issue by matslindh** [imbo/imbo#519]
When Imbo is installed through composer, having local variable names (such as `$config`) leaks into the main config file. Since the main config file also have a variable named `$config`, the default config is overwritten.

After a short discussion on IRC, we'll probably solve this by wrapping the require in a closure.

**Comment by christeredvartsen** [comment]
Might as well rename the main variable in `config.default.php` to `$defaultConfig` for good measure.

**Comment by matslindh** [comment]
Fixed in #520
