### ISSUE TITLE
Suspected race condition in src/Database/Doctrine.php insertImage()

### ISSUE THREAD

**Issue by benhackett4** [imbo/imbo#521]
This is all assuming mysql is used.

If the same image is inserted a bunch of times very quickly, I believe there is a race condition. I used to work on a project that occasionally failed to upload images, and I think this is the cause. But I no longer have access to the project or the environment so I cannot say for sure.

Basically, you could end up trying to insert records in mysql with the same imageIdentifier.

Presumably one could easily reproduce by temporarily adding a sleep statement in insertImage()

**Comment by christeredvartsen** [comment]
Thanks for the heads up! @matslindh might have some extra information regarding this.

**Comment by matslindh** [comment]
Which version of Imbo are we talking about? Since we've changed the default identifier generator from the md5 hash of the image (early versions of Imbo) to a randomly generated identifier for each image (recent versions), each image should now get its own, unique ID generated when inserted into the backend store.

But if we don't already have a unique constraint on the image identifier column in the images table, we should add it anyway - since people might be using different image identifier generators (and the random generator could end up generating the same random string within the same millisecond, although that probability is practically negligible).

**Comment by benhackett4** [comment]
No problemo. Hey wait a second shouldn't I be the one thanking you guys? :D Thanks!!

Ohhhh it must be an old version of Imbo because I'm pretty sure it was using a hash of the image path, not a random string.

So regarding the unique constraint, you guys already have it, and that is what I am pretty sure was causing the issues. I should have mentioned this in my original post, but basically if I recall correctly PDO was raising an exception and crashing, something like "can't add record because of unique key".

I'm not even really sure how one would fix this without a lot of work, because I believe all PDO exceptions are instances of the exact same class. I guess you could catch PDO exceptions and then rethrow or swallow based on a string comparison of the exception message, but that sounds brittle and I suppose you could still end up swallowing legit other unique constraint exceptions.. :\ So I guess this is a bad solution.

Maybe it is worth doing something like "INSERT ... ON DUPLICATE KEY UPDATE", but that seems to require raw mysql rather than doctrine abstractions. In fact it seems like all of the solutions in
http://stackoverflow.com/questions/1361340/how-to-insert-if-not-exists-in-mysql
require straight mysql since doctrine provides no functions for any of those mysql queries.

I'll leave it to you guys to decide if it is worth worrying about the very unlikely scenario of a race condition with randomly generated image identifiers. And I'll tell the project maintainers of the project I used to work on that they should update Imbo :)

**Comment by matslindh** [comment]
I'm not happy about doing an update either, as duplicate image ids probably should be a error condition. 

For situations involving a non-changing ID (deterministic generators) for a particular image (such as md5/etc. ids), returning a `409 Conflict` is an option, but I think I agree that just saying "everything went OK" and mostly doing a NO-OP would be preferable. We could set a header (X-Imbo-Duplicate" or something similar) to indicate that we already know about the identifier.

For cases where we generate the ID, we [do currently have a race condition](https://github.com/imbo/imbo/blob/eb39edfcd6a9c6515c1613fedef25b29151e7477/src/Image/ImagePreparation.php#L124). In a freak accident we could generate the same identifier in two separate threads before the imageExists call returns true. I'm not sure if that probability is worth losing any sleep over, but a future rewrite could handle it by trying to insert the imageIdentifier into the backend first, and then use the imageIdentifier on success, compared to using `imageExists()` to determine if the identifier should be accepted.

This would require us to make us couple the preparation/storage/insertion more tightly than it currently is, so it would be a slight design change regarding how we process input.

**Comment by matslindh** [comment]
I think we can fix this by moving the image id generation request from imagePreparation to the image storage operation, but I'm not sure it it'll break additional functionality (i.e. we would have to require that DB operations happen before storage operations or any other operation that depend on the image identifier). We'd have to store the image row, then clean it up afterwards if the storage operation fails later in the chain. Maybe @christeredvartsen has any additional suggestions?

**Comment by christeredvartsen** [comment]
> @matslindh I would suggest wrapping id generation around triggering the db.image.insert event in that case, and re-triggering it until successful IF we have a non-deterministic ID generation algorithm.

This sounds like something that could work.

**Comment by matslindh** [comment]
I've created a PR that attempts to fix this - #522. It'd be nice if you could give it a read and identify any potential issues.

**Comment by benhackett4** [comment]
@matslindh you're talking to Christer, right? If you're talking to me, then I'm sorry to be lame but I don't think I can help, sorry

**Comment by matslindh** [comment]
@benhackett4 No problem, just wanted to make sure that you saw it as well if you wanted to have chime in. I'll put all my trust in @christeredvartsen then.

**Comment by christeredvartsen** [comment]
> I'll put all my trust in @christeredvartsen then.

Said no one. Ever.
