### ISSUE TITLE
Don't assume sequence of associative keys in metadata

### ISSUE THREAD

**Issue by matslindh** [imbo/imbo#527]
The [current test in DatabaseTests for updateAndGetMetadata](https://github.com/imbo/imbo/blob/develop/tests/phpunit/integration/Database/DatabaseTests.php#L204) assumes that the sequence of associative array keys are kept when storing metadata.

I see no reason why this assumption should hold true, as associative keys will be unique, and the ordering of the keys are not guaranteed in most languages. This test passes on Doctrine based on the properties on the underlying RDBMS, and thus should be made more lax.

My current implementation in the Cassandra driver is:

        $store = ['foo' => 'foo', 'bar' => 'foo'];
        ksort($store);
        $this->assertTrue($this->adapter->updateMetadata($user, $imageIdentifier, $store));

        $fetch = $this->adapter->getMetadata($user, $imageIdentifier);
        ksort($fetch);
        $this->assertSame($store, $fetch);

.. which compares the actual arrays keys and contents, instead of expecting a certain ordering of the keys.

**Comment by christeredvartsen** [comment]
This has been resolved
