### ISSUE TITLE
Exception on reupload same image with imageVariations enabled

### ISSUE THREAD

**Issue by sgasser** [imbo/imbo#555]
Hi,

if I upload an image already existing on imbo server and imageVariations is enabled I get following error (Duplicate entry):

```
'INSERT INTO imagevariations (added, publicKey, imageIdentifier, width, height) VALUES (?, ?, ?, ?, ?)' with params [1499691870, "mediaservice", "fddcfd325761c4580273f932fd725b6b", 2000, 1331]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'mediaservice-fddcfd325761c4580273f932fd725b6b-2000' for key 'PRIMARY' in /var/www/imbo/public/index.php on line 25
```

I'm using version 1.2.*.
If I upgrade to 2 this issue is resolved?

Thanks

**Comment by christeredvartsen** [comment]
I will investigate this behavior. You are currently running `1.2.5`?

**Comment by sgasser** [comment]
Yes. Great

**Comment by sgasser** [comment]
Hi @christeredvartsen,

this issue is not resolved yet.

Should I create a PR for doctrine?

**Comment by christeredvartsen** [comment]
> Should I create a PR for doctrine?

:+1:
