### ISSUE TITLE
Getting started tutorial

### ISSUE THREAD

**Issue by Remo** [imbo/imbo#561]
I'm starting to feel really stupid. I've worked with composer and PHP for a long long time, but imbo just doesn't want to work. I'm really surprised because I thought that everything is documented, but I keep on finding small details which are missing and I keep on going back and forth to finally get this up and running.

I'd like to make a proposal because I feel that you have a great piece of software with really nice code, but if the installation is full of pitfalls it will certainly keep people away and frustrated. I really think that there should be a "getting started" tutorial which goes through the basic steps and shows you how to connect to the server afterwards. I'd be willing to help you guys, but I'd need some feedback from someone who knows imbo. I could create a markdown file and put my steps in it, if someone would be willing to give me feedback I'd be happy to write that tutorial! So far I get the impression that it would also require changes, had to change `composer.json` to get past the installation https://github.com/ortic/imbo/commit/265993ddfaf17115dc8ccc142522f0739eddd164. Not sure how we would handle this, but I don't think we can expect everyone who just wants to have a sneak peak to have mongodb installed, especially since it's not required.

**Comment by christeredvartsen** [comment]
I'd love to include a "getting started" or some other form of tutorial in the docs, and also perhaps a separate section in the main README file.

Btw, if you have a look at `composer.json` in the `develop` branch the `mongodb/mongodb` entry is no longer listed in `require`, but in `require-dev`. The `develop` branch will be the next major release of Imbo (v3.0.0).

**Comment by Remo** [comment]
Okay, I'll put that on my list. I don't think `require-dev` works. I think when I tried that yesterday it still tried to resolve the dependencies whenever I ran `composer update`, it should work fine with `composer install`, but the way it's documented won't start with a lock file.

**Comment by Remo** [comment]
Sorry, you're right, `dev-develop` seems to work. I'll use that in the tutorial for now..

**Comment by christeredvartsen** [comment]
There are two different ways of looking at the installation of Imbo. **1)** If you want to install Imbo for development purposes (as in making internal changes) you should fork the repository, make sure you have all dependencies you need for development (like MongoDB for instance), then run `composer install`, which includes dependencies from `require-dev` by default. **2)** If you want to run Imbo for regular usage you should ideally create a local `composer.json` file, which basically only has:

```json
{
  "name": "my-imbo-installation",
  "require": {
    "imbo/imbo": "<version>"
  }
}
```

then run `composer install`. This pulls Imbo from packagist, and installs only the dependencies from the `require` part of Imbos `composer.json`. This method of installation is mentioned here: http://docs.imbo.io/en/latest/installation/installation.html#using-composer

Currently the released versions does in fact have MongoDB in the `require` part of Imbos `composer.json`, but if you set the `<version>` above to `dev-develop` you might be good to go.

If you could open up a pull request against `develop`, and start adding a "getting started" or "get up and running with Imbo quick" or something like that in the main README.md file we would go from there?

I really appreciate the feedback, and before the release of Imbo-3 we have plans on giving the docs a lot of love.

**Comment by Remo** [comment]
Thanks! Will create a new pull request with a work-in-progress soon. Let's make sure the installation works for everyone!
