### ISSUE TITLE
Store image with Extension

### ISSUE THREAD

**Issue by nicholas-loulloudes** [imbo/imbo#564]
Hi, 

Is it possible to store the image in the format `"imageIdentifier"."ext"`?

Thanks.

**Comment by matslindh** [comment]
Not at the moment, but you can write a custom generator (my suggestion would be to make a generator that takes another generator as its argument and appends the suffix / extension to the generated ID).

See how the [RandomString](https://github.com/imbo/imbo/blob/develop/src/Image/Identifier/Generator/RandomString.php) generator works. The method that generates the ID receives the `Model\Image` class as its argument, which has the extension directly available.

**Comment by nicholas-loulloudes** [comment]
Just done it. My main aim was to store complete filename+extension to S3.

Extended the store() function of StorageInterface, S3 and StorageOperations Listener.

**Comment by christeredvartsen** [comment]
> @nicholas-loulloudes Extended the store() function of StorageInterface, S3 and StorageOperations Listener.

Is your solution public somewhere?

**Comment by nicholas-loulloudes** [comment]
Currently not. However, I will create a Pull Request so they can be merged into imbo anytime in the future.
I will post the request here later today.

**Comment by christeredvartsen** [comment]
@nicholas-loulloudes Can we close this issue for now?

**Comment by nicholas-loulloudes** [comment]
@christeredvartsen  Yes. I am closing it. Thanks for the help.
