### ISSUE TITLE
Imbo behind nginx reverse proxy results in authentication error 400 Signature Mismatch

### ISSUE THREAD

**Issue by Der-Alex** [imbo/imbo#590]
Hi there. 
I am running an imbo instance with a nginx webserver on a subdomain "imbo.example.com" which works well unless I use a reverse proxy. 
As a test scenario I created the imbo server and the reverse proxy on the same server with different ports and different subdomains (imbo.example.com / img-cache.example.com:1337). When I use a basic js-imboclient and change my configuration to the proxy server, I run into the error response "404 Signature mismatch". 

my proxy configuration is kind of basic: 
```
proxy_cache_path /var/www/img-cache.example.com levels=1:2 
keys_zone=imagecache:10m max_size=1000m inactive=60m use_temp_path=off;

server {
  server_name img-cache.example.com;
  listen 1337;
  client_max_body_size 10M;
  error_log /var/log/nginx/imgcache.error_log;
  access_log /var/log/nginx/imgcache.access_log;

  location / {
    proxy_pass         http://imbo.example.com;
    proxy_cache        imagecache;
    add_header 'X-Forwarded-Host' "imbo.examplecom" always;
  }
}
```

Also I tried to configure a trusted proxy with 127.0.0.1 and the external ip address but both without success. 

Do you have any advice what I am doin wrong or is it a bug I am running in?
Thanks in advance. Alex

**Comment by christeredvartsen** [comment]
I'll create a similar setup and test it later today.

**Comment by christeredvartsen** [comment]
I seem to have got it working locally.

First, I added `imbo-public` and `imbo-internal` to my `/etc/hosts` file for `127.0.0.1`. The configuration I used for Nginx:

```
server {
  server_name imbo-internal;
  listen 1337;

  root /sites/imbo/public;
  index index.php;

  access_log /var/log/nginx/imbo-internal.access_log;
  error_log /var/log/nginx/imbo-internal.error_log;

  location / {
    try_files $uri $uri/ /index.php?$args;
  }

  location ~ \.php$ {
    fastcgi_pass unix:/run/php/php7.1-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME /sites/imbo/public/index.php;
    include fastcgi_params;
  }
}

proxy_cache_path /tmp/imbo-proxy-cache levels=1:2
keys_zone=imagecache:10m max_size=1000m inactive=60m use_temp_path=off;

server {
  server_name imbo-public;
  listen 80;

  access_log /var/log/nginx/imbo-public.access_log;
  error_log /var/log/nginx/imbo-public.error_log;

  location / {
    proxy_pass http://imbo-internal:1337;
    proxy_cache imagecache;
    proxy_set_header X-Forwarded-Host imbo-public;
  }
}
```

Last I added `'127.0.0.1'` to the [`trustedProxies`](http://docs.imbo.io/en/latest/installation/configuration.html#trusted-proxies-trustedproxies) configuration option in Imbo.

I might have misunderstood something about your configuration though, so if the above is way off, please supply some more information so I can debug some more.

If I somehow managed to fix your problem, feel free to close the issue.

**Comment by Der-Alex** [comment]
Hi @christeredvartsen. Thanks for your reply. I tested your config and now I get the response " Error HTTP 400 Incorrect Access Token" when trying to list images with the imbo js client.

I checked my Access Control config, which is basically a SimpleArrayAdapter: 

```
<?php
return [
    'accessControl' => function() {
        return new Imbo\Auth\AccessControl\Adapter\SimpleArrayAdapter([
            'username' => 'mysecret',
            'anotheruser' => 'othersecret'
        ]);
    }
];
```

My Client js is very basic too: 

```
var Imbo = require('imboclient');
var client = new Imbo.Client({
    hosts: 'http://img-cache.example.com',
    user: 'username',
    publicKey: 'username',
    privateKey: 'mysecret'
});
var url = client.getUserUrl();
console.log(url); //works

client.getImages(function(err, images, search) {
  if (err) {
    return console.error('Oh no, an error occured: ' + err);
  }
  console.log('Images on the server: ' + search.hits);
  images.forEach(function(image) {
    console.log(image.imageIdentifier)
  });
});
```

Any Ideas?
