### ISSUE TITLE
When file storage is unavailable, imbo outputs 200 OK with invalid body.

### ISSUE THREAD

**Issue by lkarsten** [imbo/imbo#591]
Issue: If file storage is unavailable, imbo will reply with 200 OK and an empty/invalid response body.

Expected: 500 Server Unavailable response code.

When running imbo behind Varnish Cache, the erroneous body will be kept around and served to lots and lots of clients, even if the storage comes back online. This will also apply to any distributed/local caches out there.

Rough patch:
```
--- /var/www/sites/imbo3/vendor/imbo/imbo/src/Storage/Filesystem.php    2017-10-11 11:52:37.656849329 +0200
+++ Filesystem.php      2017-12-20 10:00:21.367243651 +0100
@@ -111,7 +111,13 @@
 
         $path = $this->getImagePath($user, $imageIdentifier);
 
-        return file_get_contents($path);
+        $imagedata = file_get_contents($path);
+
+        if ( $imagedata === false ) {
+           throw new StorageException('Error reading file', 500);
+       }
+
+        return $imagedata;
     }
 
     /**
```

Original imbo debugging and patch by Carl-Christian Salvesen.

**Comment by lkarsten** [comment]
Hi. Do you need any further information to move this along?

**Comment by christeredvartsen** [comment]
I'll try to have a look at this later this week or early next week.
