### ISSUE TITLE
Exception 'Invalid storage adapter' when using FileSystem Storage

### ISSUE THREAD

**Issue by Vladosama** [imbo/imbo#594]
I have modified the config.default.php to use filesystem storage as below:

...
'storage' => function() {
         new Storage\Filesystem([
             'dataDir' => 'E:\work\Playground\image_server\data',
         ]);
     },
...

and I got following exception:

Fatal error: Uncaught Exception with message: Invalid storage adapter in E:\work\Playground\image_server\imbo\public\index.php on line 30

**Comment by christeredvartsen** [comment]
Did you forget a `return` statement in the anonymous function?

**Comment by christeredvartsen** [comment]
And please don't update `config.default.php`. Create a `config.php` script to override the default values:

```php
// config/config.php
use Imbo\Storage;

return [
    // ...

    'storage' => function() {
        return new Storage\Filesystem([
            'dataDir' => 'E:\work\Playground\image_server\data',
        ]);
    },

    // ...
];
```

Read more about the configuration files here: http://docs.imbo.io/en/latest/installation/installation.html#installation

**Comment by Vladosama** [comment]
@christeredvartsen oops, you are right...thx a lot!  (sorry for the late reply，it's Ching Ming Festival in China,
