### ISSUE TITLE
unable to setup on ubuntu16.04 with mysql, getting exception

### ISSUE THREAD

**Issue by pavanyogi** [imbo/imbo#602]
[Tue Jan 22 15:13:33.069288 2019] [php7:error] [pid 14870] [client 127.0.0.1:42476] PHP Fatal error:  Uncaught Exception with message: Invalid database adapter in /home/project/imbo/public/index.php on line 30

**Comment by christeredvartsen** [comment]
The error seemed to be caused by a misconfigured hostname. Not really related to Imbo.
