### ISSUE TITLE
File storage, not only images

### ISSUE THREAD

**Issue by ed-fruty** [imbo/imbo#603]
Hi.

Sorry, I'm new in your package. 
But I have a question. Can `imbo` be used for any files storage (like pdf, djvu, etc.), not only for images?
Or it would be better to use another tool ?

**Comment by ed-fruty** [comment]
@matslindh , @christeredvartsen ping ;)

**Comment by christeredvartsen** [comment]
I would use a different tool for storing other types of documents. Imbo is created as a tool for dynamically transforming images and not as a generic file storage.

**Comment by ed-fruty** [comment]
@matslindh , @christeredvartsen, thanks a lot!

And maybe you can advice some ready tool for generic file storage based on your experience ? (images, pdf, etc.)

**Comment by matslindh** [comment]
Backblaze B2 and Google Cloud Storage has served us well for more static resources.
