### ISSUE TITLE
Use GitHub Actions instead of Travis-CI

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#608]
Move from Travis-CI to using GitHub Actions

**Comment by peter279k** [comment]
The GitHub action setup has following approach:

- Creating the directory named `.github/workflows` and add the `yml` file on that folder.

I think I can try to migrate the `.travis.yml` setting to `GitHub actions` :).

**Comment by christeredvartsen** [comment]
The task has already been done. I have a bunch of local development branches locally that has fixes for a few of the issues mentioned here. I will try to push some of them soon-ish.

**Comment by christeredvartsen** [comment]
Resolved
