### ISSUE TITLE
Generic cleanup of code base

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#609]
Some generic stuff that should be cleaned up:

- [x] Remove copyright docblock from all files (7b179210c656f7a1f709582399d478e36eb37b58)
- [x] Remove unused `use` statements
- [x] Remove all `@group` annotations from PHPUnit tests (52da2a571d331a02cc40c273daf5b08268be8272)
- [x] Use `@coversDefaultClass` instead of `@covers` in class level docblocks (9876470258a6be17372b9acaec11b412acbdba09)
- [x] Use multiple `use` statements (960cb78dc43c0e4bb320e01d883932f88a9bd34f)
- [ ] ~~Add `declare(strict_types=1);`~~ (will be fixed as a part of #619)
- [ ] ~~Add type hints where applicable~~ (will be fixed as a part of #619)
- [x] Remove all `@author` docblocks (541cf64f7846db80ee0ea9bc19b83a8b9b6cd143)
- [x] Remove all `@package` docblocks (7b3c8db3bf7573aab3de0f686ed68f5def5c3401)

The above list will likely be updated with new entries.

**Comment by peter279k** [comment]
It seems that the `Remove unused use statements` and `Add declare(strict_types=1);` are unchecked.

If possible, I can work on these unchecked works :).
