### ISSUE TITLE
Add static analysis tools

### ISSUE THREAD

**Issue by christeredvartsen** [imbo/imbo#619]
And https://phpstan.org/ and/or https://psalm.dev/ and use them as a part of the workflow.

**Comment by peter279k** [comment]
Which PHPStan level should be for this repository?

I think we can use the `max` level for this repository.

**Comment by christeredvartsen** [comment]
> I think we can use the `max` level for this repository.

I haven't decided  yet. I have started working on a branch for this locally, will push soon-ish.
