### ISSUE TITLE
Docker support and documentation

### ISSUE THREAD

**Issue by bjornarhagen** [imbo/imbo#632]
Hey I'm looking to spin up this project and give it a try.
It seems the link to your documentation no longer work (in the README).

Also I found this repo, but the last update was 6 years ago. https://github.com/imbo/imbo-docker

So I'm wondering if there are any docs anywhere, and is there an official Docker image that is up to date?

**Comment by matslindh** [comment]
The current docs are located at https://imbo.readthedocs.io/en/latest/ - I'll make a PR to update the reference in `README.md`. There is no other official docker image, but I'm currently dockerizing one of our imbo installations. Maybe we can use that as an update later.

**Comment by bjornarhagen** [comment]
Alright thanks for the info! :)
